# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  FIREBASE_API_KEY: base64_encoded_value
  FIREBASE_AUTH_DOMAIN: base64_encoded_value
  # diğer değişkenler...

# Not: Değerler base64 ile encode edilmelidir.
# Örneğin: echo -n 'your_value' | base64
