apiVersion: v1
kind: Service
metadata:
  name: easyreadbackend-service
spec:
  selector:
    app: easyreadbackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
